In [2]:
import sys
import os
import math
from math import pi
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from scipy.fftpack import fft, ifft
from mpl_toolkits.mplot3d import Axes3D


In [3]:
def c_vec(v1,v2):
    n,_=v1.shape
    c=np.zeros((n,3))
    c[:][0]=v1[:][1]*v2[:][2]-v1[:][2]*v2[:][1]
    c[:][1]=v1[:][2]*v2[:][0]-v1[:][0]*v2[:][2]
    c[:][2]=v1[:][0]*v2[:][1]-v1[:][1]*v2[:][0]
    return c
a=np.arange(1,10)
b=np.arange(1,4)
v1,v2=np.meshgrid(b,a)

c=c_vec(v1,v2)
print(c)

[[ 1.  2.  3.]
 [-2. -4. -6.]
 [ 1.  2.  3.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
